# Generated by Django 3.1.4 on 2021-01-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_price',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='song_price',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='track',
            field=models.IntegerField(default=0),
        ),
    ]
