# Generated by Django 3.1.4 on 2021-01-03 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210103_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateField(default=datetime.date(2021, 1, 3)),
        ),
    ]
