# Generated by Django 3.1.4 on 2021-01-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_remove_album_album_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('track', models.IntegerField(default=0)),
                ('song_title', models.CharField(max_length=255)),
                ('song_price', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
