# Generated by Django 3.1.4 on 2021-01-04 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20210104_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single',
            name='track',
        ),
        migrations.AddField(
            model_name='single',
            name='artist',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='single',
            name='genre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='single',
            name='song_logo',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.IntegerField(default=1),
        ),
    ]
