# Generated by Django 3.1.4 on 2021-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20210104_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_date',
            field=models.DateField(default='2020-12-12'),
        ),
    ]
