# Generated by Django 3.1.4 on 2021-01-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_song_song_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_date',
        ),
        migrations.AddField(
            model_name='single',
            name='song_date',
            field=models.DateField(default='2020-12-12'),
        ),
    ]
