# Generated by Django 3.1.4 on 2021-01-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_auto_20210105_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='song_file',
            field=models.FileField(default='art.png', upload_to=''),
            preserve_default=False,
        ),
    ]
