# Generated by Django 3.1.4 on 2021-01-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_single_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default='best.mp3', upload_to=''),
            preserve_default=False,
        ),
    ]
