# Generated by Django 3.1.4 on 2021-01-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_song_song_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
    ]
