# Generated by Django 3.1.4 on 2021-01-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20210127_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RemoveField(
            model_name='single',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='single',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='single',
            name='song_logo',
        ),
        migrations.RemoveField(
            model_name='single',
            name='song_title',
        ),
        migrations.AddField(
            model_name='single',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='single',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='single',
            name='artist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='single',
            name='song_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='single',
            name='song_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
