# Generated by Django 3.1.4 on 2021-01-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_auto_20210127_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='single',
            old_name='song_date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='single',
            old_name='song_price',
            new_name='price',
        ),
    ]
