# Generated by Django 3.1.4 on 2021-01-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_auto_20210127_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
    ]
