# Generated by Django 3.1.4 on 2021-02-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_file',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='digital',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='single',
            name='digital',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='digital',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
