# Generated by Django 3.1.4 on 2021-01-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='country',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='province',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
