# Generated by Django 3.1.4 on 2021-02-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='link',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
    ]
